const POSTHOG_KEY = process.env.NEXT_PUBLIC_POSTHOG_KEY;
const POSTHOG_HOST = process.env.NEXT_PUBLIC_POSTHOG_HOST;
const POSTHOG_PERSONAL_KEY = process.env.NEXT_PUBLIC_POSTHUG_PERSONAL_KEY;
export { POSTHOG_HOST, POSTHOG_KEY, POSTHOG_PERSONAL_KEY };
